






/* eslint-disable @typescript-eslint/no-explicit-any */
"use client"
import {useEffect,useMemo,useState} from "react"
import {useRouter} from "next/navigation"
import {onAuthStateChanged,signOut} from "firebase/auth"
import {collection,doc,getDoc,getDocs,query,where} from "firebase/firestore"
import {auth,db} from "@/app/lib/firebase"
import {getQuizDef} from "@/app/data/quizCatalog"
type A=Record<string,any>
type R={id:string;name:string;email:string;count:number;score:number|null;last:Date|null;status:string;course:string}
const tabs=["Dashboard","Learners","Courses","Analytics","Reports","Company"] as const
const d=(v:any):Date|null=>{if(!v)return null;const x=typeof v.toDate==="function"?v.toDate():v.seconds?new Date(v.seconds*1000):typeof v==="number"&&v<100000000000?new Date(v*1000):new Date(v);return Number.isNaN(x.getTime())||x.getTime()>Date.now()+86400000?null:x}
const score=(x:A)=>{if(Number.isFinite(x.accuracy))return x.accuracy<=1?x.accuracy*100:Math.min(100,Math.max(0,x.accuracy));const c=Number(x.correctCount??x.score),t=Number(x.totalQuestions??x.total??x.answeredCount);return Number.isFinite(c)&&Number.isFinite(t)&&t>0?Math.min(100,Math.max(0,c/t*100)):null}
const pct=(x:number|null)=>x==null?"—":Math.round(x)+"%"
const fmt=(x:Date|null)=>x?x.toLocaleDateString("ja-JP"):"—"
const courseLabel=(id:string)=>{try{return getQuizDef(id)?.title??id}catch{return id||"教材未設定"}}
const jstDay=(x:Date)=>Math.floor((x.getTime()+32400000)/86400000)
export default function BusinessDashboard({appName,loginHref="/company/login",companyField="companyCode"}:{appName:string;loginHref?:string;companyField?:"companyCode"|"companyId"}){
 const router=useRouter(),[tab,setTab]=useState<(typeof tabs)[number]>("Dashboard"),[rows,setRows]=useState<R[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[company,setCompany]=useState<A>({}),[code,setCode]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("すべて"),[sort,setSort]=useState("last"),[menu,setMenu]=useState(false),[copied,setCopied]=useState(false)
 useEffect(()=>onAuthStateChanged(auth,async user=>{if(!user){router.replace(loginHref);return}try{const ms=await getDoc(doc(db,"users",user.uid));if(!ms.exists())throw Error("管理者情報が見つかりません。");const me=ms.data() as A,role=String(me.role??"");if(!["admin","company_admin"].includes(role))throw Error("閲覧権限がありません。");const cc=String(me[companyField]??"");if(role!=="admin"&&!cc)throw Error("企業コードがありません。");setCode(cc);if(cc){const cs=await getDoc(doc(db,"companies",cc));setCompany(cs.exists()?cs.data():{name:me.companyName})}const users=collection(db,"users"),snap=role==="admin"&&!cc?await getDocs(users):await getDocs(query(users,where(companyField,"==",cc))),people=snap.docs.map(x=>({id:x.id,...x.data()} as A)).filter(x=>x.id!==user.uid&&!String(x.role??"").includes("admin"));setRows(await Promise.all(people.map(async p=>{const [rs,ps]=await Promise.all([getDocs(collection(db,"users",p.id,"results")),getDocs(collection(db,"users",p.id,"progress"))]),results=rs.docs.map(x=>x.data() as A),progress=ps.docs.map(x=>({id:x.id,...x.data()} as A)),vals=results.map(score).filter((x):x is number=>x!=null),dates=[...results.map(x=>d(x.completedAt??x.createdAt??x.lastStudyAt??x.updatedAt)),...progress.map(x=>d(x.lastStudyAt??x.lastStudiedAt??x.completedAt??x.updatedAt??x.lastStudyDate))].filter((x):x is Date=>!!x),last=dates.length?new Date(Math.max(...dates.map(x=>x.getTime()))):null,count=results.length||progress.reduce((n,x)=>n+Number(x.totalSessions??0),0);return{id:p.id,name:String(p.displayName??p.name??"名前未設定"),email:String(p.email??""),count,score:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,last,status:!count?"未学習":last&&jstDay(new Date())-jstDay(last)>=7?"要フォロー":"学習中",course:courseLabel(String(results[0]?.quizType??results[0]?.courseId??results[0]?.materialId??progress[0]?.quizType??progress[0]?.courseId??progress[0]?.materialId??progress[0]?.id??""))}})))}catch(e){setError(e instanceof Error?e.message:"取得に失敗しました")}finally{setLoading(false)}}),[router,loginHref,companyField])
 const shown=useMemo(()=>rows.filter(x=>(filter==="すべて"||x.status===filter)&&(x.name+" "+x.email).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name,"ja"):sort==="count"?b.count-a.count:sort==="score"?(b.score??-1)-(a.score??-1):(b.last?.getTime()??0)-(a.last?.getTime()??0)),[rows,search,filter,sort]),avg=rows.map(x=>x.score).filter((x):x is number=>x!=null)
 const exportCsv=()=>{const data=[["氏名","メール","状態","学習回数","平均正答率","最終学習日","教材"],...shown.map(x=>[x.name,x.email,x.status,x.count,pct(x.score),fmt(x.last),x.course])],safe=(v:unknown)=>{const s=String(v);return '"'+(["=","+","-","@"].includes(s.charAt(0))?"'":"")+s.replaceAll('"','""')+'"'},blob=new Blob(["\uFEFF"+data.map(x=>x.map(safe).join(",")).join("\r\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=appName+"-learners-"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(a.href)}
 const copyCode=async()=>{if(!code)return;try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(code);else{const t=document.createElement("textarea");t.value=code;document.body.appendChild(t);t.select();document.execCommand("copy");t.remove()}setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setError("企業コードをコピーできませんでした。手動で選択してコピーしてください。")}}
 if(loading)return <main style={s.center}>読み込み中…</main>
 return <div style={s.shell}><style>{responsive}</style><aside className={menu?"bdSide open":"bdSide"} style={s.side}><h2>OutIN Academy</h2><small>Business Dashboard<br/>企業向け学習管理画面</small><b style={s.app}>{appName}</b><a href="/home" style={{color:"white",padding:10}}>アプリへ戻る</a>{tabs.map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?s.on:s.nav}>{x}</button>)}<button onClick={()=>signOut(auth)} style={s.nav}>ログアウト</button></aside>{menu&&<button className="bdScrim" onClick={()=>setMenu(false)} aria-label="メニューを閉じる"/>}<main className="bdMain" style={s.main}><header style={s.head}><button className="bdHamb" onClick={()=>setMenu(true)} aria-label="メニューを開く">☰</button><b>{tab}</b><span>{company.name??company.companyName??code}</span></header><div style={s.content}>{error?<div style={s.card}>{error}</div>:<><h1>{tab}</h1>{tab==="Dashboard"&&<div style={s.grid}><Card a="登録学習者数" b={rows.length}/><Card a="学習中" b={rows.filter(x=>x.status==="学習中").length}/><Card a="要フォロー" b={rows.filter(x=>x.status==="要フォロー").length}/><Card a="平均正答率" b={pct(avg.length?avg.reduce((a,b)=>a+b,0)/avg.length:null)}/></div>}{tab==="Learners"&&<><div style={s.tools}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="氏名・メールで検索" aria-label="氏名またはメールで検索"/><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="状態フィルター">{["すべて","未学習","学習中","要フォロー"].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="並び替え"><option value="last">最終学習日</option><option value="name">氏名</option><option value="count">学習回数</option><option value="score">平均正答率</option></select><button onClick={exportCsv}>CSV出力</button></div><div style={s.table}><table><thead><tr>{["氏名","状態","学習回数","平均正答率","最終学習日","教材"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>{x.name}</b><small>{x.email}</small></td><td>{x.status}</td><td>{x.count}</td><td>{pct(x.score)}</td><td>{fmt(x.last)}</td><td>{x.course}</td></tr>)}</tbody></table></div></>}{tab==="Courses"&&<div style={s.card}>実データに存在する教材: {[...new Set(rows.map(x=>x.course))].join("、")||"集計データなし"}</div>}{tab==="Analytics"&&<div style={s.card}>平均正答率 {pct(avg.length?avg.reduce((a,b)=>a+b,0)/avg.length:null)} ／ 学習中 {rows.filter(x=>x.status==="学習中").length}名</div>}{tab==="Reports"&&<div style={s.card}><p>出力対象 {shown.length}件</p><button onClick={exportCsv}>学習者一覧CSVを出力</button><p>PDFレポートは準備中です。</p></div>}{tab==="Company"&&<div style={s.card}><p>会社名: {String(company.name??company.companyName??"—")}</p><p>企業コード: {code||"—"}</p><p>契約状態: {String(company.status??"有効")}</p><p>登録学習者数: {rows.length}名</p><p>利用中のアプリ: {appName}</p><button onClick={copyCode} disabled={!code}>{copied?"コピーしました":"企業コードをコピー"}</button></div>}</>}</div></main></div>
}
const Card=({a,b}:{a:string;b:any})=><article style={s.card}><span>{a}</span><strong style={s.num}>{b}</strong></article>
const s:Record<string,React.CSSProperties>={shell:{minHeight:"100vh",background:"#f5f7fb",color:"#10213b",fontFamily:"system-ui"},side:{position:"fixed",inset:"0 auto 0 0",width:250,padding:22,background:"#102342",color:"white",display:"flex",flexDirection:"column",gap:10},app:{padding:"15px 0"},nav:{padding:12,border:0,borderRadius:10,background:"transparent",color:"#ccd7e8",textAlign:"left"},on:{padding:12,border:0,borderRadius:10,background:"white",color:"#102342",textAlign:"left"},main:{marginLeft:250},head:{height:70,padding:"0 28px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"white"},content:{maxWidth:1200,margin:"auto",padding:28},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:15},card:{padding:22,background:"white",border:"1px solid #e2e8f0",borderRadius:18,marginBottom:15},num:{display:"block",fontSize:30,marginTop:10},tools:{display:"flex",gap:10,marginBottom:15},table:{overflowX:"auto",background:"white",borderRadius:16},center:{minHeight:"100vh",display:"grid",placeItems:"center"}}




const responsive=`.bdHamb,.bdScrim{display:none}@media(max-width:800px){.bdSide{transform:translateX(-105%);transition:transform .2s}.bdSide.open{transform:none}.bdMain{margin-left:0!important}.bdHamb{display:block}.bdScrim{display:block;position:fixed;inset:0;border:0;border-radius:0;background:#09142688;z-index:20}}@media(max-width:430px){.bdMain header{padding:0 12px!important}.bdMain>div{padding:18px!important}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #ff9a65;outline-offset:2px}`





